
//def ReleaseDir = "c:\inetpub\wwwroot"
pipeline {
			agent any
			stages {
				stage('Source'){
					steps{
						checkout([$class: 'GitSCM', branches: [[name: '*/main']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '825fc4d4-4161-4170-9587-28a936f82af6', url: 'https://github.com/finansu-cl/finansuProd.git']]])
					}
				}
				stage('Build') {
    					steps {
    					    bat "\"${tool 'MSBUild'}\" sifacob-develop/sifacob-develop/SIFACO.sln /t:build 
    					}
				}
			}
}
